# Generated by Django 4.1.3 on 2022-12-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_friendrequest_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='UsersGroup',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
