# Generated by Django 4.1.3 on 2022-11-24 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_usersgroup_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), default=list, size=None),
        ),
    ]
